In [5]:
import plotly.express as px
import plotly.graph_objects as go
from shinywidgets import output_widget, render_widget, render_plotly
import pandas as pd

In [6]:
pop_size_instrument_df = pd.read_csv("/Users/poppyriddle/Documents/Github/ShinyShiny/dashboard-LNS/www/pop_size_instrument.csv", encoding="UTF-8")
pop_size_instrument_df

  Count of instrument_classified  ...  Test/task
0                  Not specified  ...        2.0
1                          1-100  ...        1.0
2                        100-500  ...        NaN
3                       500-1000  ...        1.0
4                      1000-5000  ...        NaN
5                     5000-10000  ...        NaN
6                         10000+  ...        NaN

[7 rows x 7 columns]

In [30]:
fig = px.bar(pop_size_instrument_df,
                y='Count of instrument_classified',
                x=['Interview/focus group',
                        'Other',
                        'Self-reported data',
                        'Standardized assessment/tool',
                        'Survey/questionnaire',
                        'Test/task'],
                #color_discrete_sequence=["red", "green", "blue", "goldenrod", "magenta","gray"],
                orientation='h',
                color_discrete_sequence= px.colors.sequential.Plotly3)
fig.update_layout(
        title="Population size by instrument",
        xaxis_title="Instrument",
        yaxis_title="Population size (participants)",
        height=400,
        width=600,
        )
fig

In [13]:
#a_time
a_time_df = pd.read_csv("www/a_time.csv", encoding="utf-8")
a_time_df

    year  Counts
0   2014      16
1   2015      13
2   2016      23
3   2017      14
4   2018      28
5   2019      19
6   2020      20
7   2021      14
8   2022      25
9   2023      17
10  2024       8

In [29]:
fig = px.bar(a_time_df, x='year', y='Counts',color='year',color_continuous_scale=px.colors.sequential.Plotly3)
fig.update_layout(
            title="Literature published over time",
            xaxis_title="Year",
            yaxis_title="Counts",
            
        )
fig

In [31]:
#plotly_a_funder_type
a_funder_type_df = pd.read_csv("www/a_funder_type.csv", encoding="UTF-8")
a_funder_type_df

            Literacy  ...  Nonprofit
0         Assessment  ...        NaN
1           Cultural  ...        NaN
2            Digital  ...        1.0
3   Essential skills  ...        NaN
4          Financial  ...        NaN
5             Health  ...        8.0
6        Ideological  ...        NaN
7        Information  ...        NaN
8           Language  ...        1.0
9               Math  ...        NaN
10             Media  ...        NaN
11    Multiliteracy   ...        NaN
12          Physical  ...        9.0
13        Scientific  ...        NaN
14       Traditional  ...        3.0

[15 rows x 7 columns]

In [32]:
fig = px.bar(a_funder_type_df,
        y='Literacy',
        x=['Academic institution/centre',
                'Corporation',
                'Government',
                'International organization',
                'No funding received or specified',
                'Nonprofit'],
        color_discrete_sequence= px.colors.sequential.Plotly3,
        orientation='h')
fig.update_layout(
                title="Funder by literacy type",
                xaxis_title="Literacy type",
                yaxis_title="Count of works",
                )
fig

In [33]:
#a_funder_concept
a_funder_concept_df = pd.read_csv("www/a_funder_concept.csv",encoding="UTF-8")
a_funder_concept_df

    Concepts  ...  Nonprofit
0     Skills  ...          9
1      Mixed  ...         10
2  Practices  ...          3

[3 rows x 7 columns]

In [35]:
#a_funder_concept
fig = px.bar(a_funder_concept_df,
        x='Concepts',
        y=['Academic institution/centre',
            'Corporation',
            'Government',
            'International organization',
            'No funding received or specified',
            'Nonprofit'],
        color_discrete_sequence=px.colors.sequential.Plotly3,
        )
fig.update_layout(
            title="Literature published over time",
            xaxis_title="Year",
            yaxis_title="Counts",
            
        )
fig